stages:
  - build_test
  - deploy

pytest:
  stage: build_test
  image: tensorflow/tensorflow:2.0.1-py3
  script:
  - pip install -r requirements.txt
  - pip install pysnooper pytest pytest-cov pytest-benchmark
  - py.test --benchmark-disable --cov=tf_pwa --doctest-modules tf_pwa

pylint:
  stage: build_test
  image: tensorflow/tensorflow:2.0.1-py3
  script:
  - pip install -r requirements.txt
  - pip install pylint pytest
  - pylint tf_pwa --errors-only --exit-zero

build_wheel:
  stage: build_test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install setuptools
    - python3 setup.py bdist_wheel

  artifacts:
    untracked: true

build_docs:
  stage: build_test
  only:
    - tags
    - triggers
    - schedules
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip make texlive-full
    - pip3 install setuptools sphinx numpy scipy matplotlib pyyaml opt_einsum sympy
    - cd docs && make latexpdf
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - docs/_build/latex/*.pdf

pages:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip
    - pip3 install setuptools sphinx numpy scipy matplotlib pyyaml opt_einsum sympy
    - python3 setup.py build_sphinx
    - cp build/sphinx/html public -R
  artifacts:
    paths:
      - public
  only:
    - tags
    - triggers
    - schedules
